name: 'Chose Action Runner'
description: 'Chose self-hosted action runner based on their availability'
inputs:
  preferred-runner:
    description: 'Runner to chose if it is available'
    required: true
  fallback-runner:
    description: 'Fallback runner if primary-runner is unavailable'
    required: true
  runners-holder:
    description: 'Repository or organization holding the self-hosted runners "repos/{user}/{repo_name}" or "orgs/{org_name}"'
    required: false
    default: repos/${{ github.repository }}
  github-token:
    description: 'GitHub API token with read access to organization self hosted runners and read access to repository administration and metadata'
    required: true
outputs:
  runner:
    description: "Chosen runner"
    value: ${{ steps.chose-runner.outputs.runner }}
runs:
  using: "composite"
  steps:
    - id: chose-runner
      shell: bash
      run: |
        runners=$(curl -s -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ inputs.github-token }}" "https://api.github.com/${{ inputs.runners-holder }}/actions/runners")
        echo $runners
        available=$(echo "$runners" | jq -r '.runners[] | select(.status == "online")' | jq -r 'select(.name | startswith("${{ inputs.preferred-runner }}"))')
        echo $available
        if [ -n "$available" ]; then
          echo "runner=${{ inputs.preferred-runner }}" >> $GITHUB_OUTPUT
        else
          echo "runner=${{ inputs.fallback-runner }}" >> $GITHUB_OUTPUT
        fi
